package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nombre;
     private String observaciones;
     private Set<Tema> temasForCategoriaIdCategoria = new HashSet<Tema>(0);
     private Set<Tema> temasForIdCategoria = new HashSet<Tema>(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(int idCategoria, String nombre, String observaciones, Set<Tema> temasForCategoriaIdCategoria, Set<Tema> temasForIdCategoria) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.temasForCategoriaIdCategoria = temasForCategoriaIdCategoria;
       this.temasForIdCategoria = temasForIdCategoria;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<Tema> getTemasForCategoriaIdCategoria() {
        return this.temasForCategoriaIdCategoria;
    }
    
    public void setTemasForCategoriaIdCategoria(Set<Tema> temasForCategoriaIdCategoria) {
        this.temasForCategoriaIdCategoria = temasForCategoriaIdCategoria;
    }
    public Set<Tema> getTemasForIdCategoria() {
        return this.temasForIdCategoria;
    }
    
    public void setTemasForIdCategoria(Set<Tema> temasForIdCategoria) {
        this.temasForIdCategoria = temasForIdCategoria;
    }




}


