package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private int idChat;
     private Consulta consulta;
     private String mensaje;
     private Date horaEnvio;
     private String enviadoPor;

    public Chat() {
    }

	
    public Chat(int idChat, Consulta consulta) {
        this.idChat = idChat;
        this.consulta = consulta;
    }
    public Chat(int idChat, Consulta consulta, String mensaje, Date horaEnvio, String enviadoPor) {
       this.idChat = idChat;
       this.consulta = consulta;
       this.mensaje = mensaje;
       this.horaEnvio = horaEnvio;
       this.enviadoPor = enviadoPor;
    }
   
    public int getIdChat() {
        return this.idChat;
    }
    
    public void setIdChat(int idChat) {
        this.idChat = idChat;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Date getHoraEnvio() {
        return this.horaEnvio;
    }
    
    public void setHoraEnvio(Date horaEnvio) {
        this.horaEnvio = horaEnvio;
    }
    public String getEnviadoPor() {
        return this.enviadoPor;
    }
    
    public void setEnviadoPor(String enviadoPor) {
        this.enviadoPor = enviadoPor;
    }




}


