package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Expertostema generated by hbm2java
 */
public class Expertostema  implements java.io.Serializable {


     private int idExpertosTema;
     private Tema tema;
     private Usuario usuario;
     private int usuarioIdUsuario;
     private int temaIdTema;
     private Set<Consulta> consultas = new HashSet<Consulta>(0);

    public Expertostema() {
    }

	
    public Expertostema(int idExpertosTema, Tema tema, Usuario usuario, int usuarioIdUsuario, int temaIdTema) {
        this.idExpertosTema = idExpertosTema;
        this.tema = tema;
        this.usuario = usuario;
        this.usuarioIdUsuario = usuarioIdUsuario;
        this.temaIdTema = temaIdTema;
    }
    public Expertostema(int idExpertosTema, Tema tema, Usuario usuario, int usuarioIdUsuario, int temaIdTema, Set<Consulta> consultas) {
       this.idExpertosTema = idExpertosTema;
       this.tema = tema;
       this.usuario = usuario;
       this.usuarioIdUsuario = usuarioIdUsuario;
       this.temaIdTema = temaIdTema;
       this.consultas = consultas;
    }
   
    public int getIdExpertosTema() {
        return this.idExpertosTema;
    }
    
    public void setIdExpertosTema(int idExpertosTema) {
        this.idExpertosTema = idExpertosTema;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public int getTemaIdTema() {
        return this.temaIdTema;
    }
    
    public void setTemaIdTema(int temaIdTema) {
        this.temaIdTema = temaIdTema;
    }
    public Set<Consulta> getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }




}


