package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private FacturaId id;
     private Consulta consulta;
     private int totalConsulta;

    public Factura() {
    }

    public Factura(FacturaId id, Consulta consulta, int totalConsulta) {
       this.id = id;
       this.consulta = consulta;
       this.totalConsulta = totalConsulta;
    }
   
    public FacturaId getId() {
        return this.id;
    }
    
    public void setId(FacturaId id) {
        this.id = id;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public int getTotalConsulta() {
        return this.totalConsulta;
    }
    
    public void setTotalConsulta(int totalConsulta) {
        this.totalConsulta = totalConsulta;
    }




}


