package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1



/**
 * FacturaId generated by hbm2java
 */
public class FacturaId  implements java.io.Serializable {


     private int idFactura;
     private String estado;

    public FacturaId() {
    }

    public FacturaId(int idFactura, String estado) {
       this.idFactura = idFactura;
       this.estado = estado;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaId) ) return false;
		 FacturaId castOther = ( FacturaId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFactura();
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


