package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idTema;
     private Categoria categoriaByCategoriaIdCategoria;
     private Categoria categoriaByIdCategoria;
     private String nombre;
     private String tipo;
     private String observaciones;
     private String estado;
     private String foto;
     private Integer precioMinuto;
     private Set<Expertostema> expertostemas = new HashSet<Expertostema>(0);

    public Tema() {
    }

	
    public Tema(int idTema, Categoria categoriaByCategoriaIdCategoria, Categoria categoriaByIdCategoria) {
        this.idTema = idTema;
        this.categoriaByCategoriaIdCategoria = categoriaByCategoriaIdCategoria;
        this.categoriaByIdCategoria = categoriaByIdCategoria;
    }
    public Tema(int idTema, Categoria categoriaByCategoriaIdCategoria, Categoria categoriaByIdCategoria, String nombre, String tipo, String observaciones, String estado, String foto, Integer precioMinuto, Set<Expertostema> expertostemas) {
       this.idTema = idTema;
       this.categoriaByCategoriaIdCategoria = categoriaByCategoriaIdCategoria;
       this.categoriaByIdCategoria = categoriaByIdCategoria;
       this.nombre = nombre;
       this.tipo = tipo;
       this.observaciones = observaciones;
       this.estado = estado;
       this.foto = foto;
       this.precioMinuto = precioMinuto;
       this.expertostemas = expertostemas;
    }
   
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public Categoria getCategoriaByCategoriaIdCategoria() {
        return this.categoriaByCategoriaIdCategoria;
    }
    
    public void setCategoriaByCategoriaIdCategoria(Categoria categoriaByCategoriaIdCategoria) {
        this.categoriaByCategoriaIdCategoria = categoriaByCategoriaIdCategoria;
    }
    public Categoria getCategoriaByIdCategoria() {
        return this.categoriaByIdCategoria;
    }
    
    public void setCategoriaByIdCategoria(Categoria categoriaByIdCategoria) {
        this.categoriaByIdCategoria = categoriaByIdCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Integer getPrecioMinuto() {
        return this.precioMinuto;
    }
    
    public void setPrecioMinuto(Integer precioMinuto) {
        this.precioMinuto = precioMinuto;
    }
    public Set<Expertostema> getExpertostemas() {
        return this.expertostemas;
    }
    
    public void setExpertostemas(Set<Expertostema> expertostemas) {
        this.expertostemas = expertostemas;
    }




}


