package cr.ac.una.prograiv.milkyway.domain;
// Generated Oct 7, 2016 8:30:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String contrasena;
     private String nombre;
     private String apellido;
     private String email;
     private Date fechaNac;
     private String dirreccion;
     private String telTrabajo;
     private String telCelular;
     private Boolean estado;
     private String tipo;
     private Set<Expertostema> expertostemas = new HashSet<Expertostema>(0);
     private Set<Consulta> consultas = new HashSet<Consulta>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String contrasena, String nombre, String apellido, String email, Date fechaNac, String dirreccion, String telTrabajo, String telCelular, Boolean estado, String tipo, Set<Expertostema> expertostemas, Set<Consulta> consultas) {
       this.idUsuario = idUsuario;
       this.contrasena = contrasena;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.fechaNac = fechaNac;
       this.dirreccion = dirreccion;
       this.telTrabajo = telTrabajo;
       this.telCelular = telCelular;
       this.estado = estado;
       this.tipo = tipo;
       this.expertostemas = expertostemas;
       this.consultas = consultas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getDirreccion() {
        return this.dirreccion;
    }
    
    public void setDirreccion(String dirreccion) {
        this.dirreccion = dirreccion;
    }
    public String getTelTrabajo() {
        return this.telTrabajo;
    }
    
    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }
    public String getTelCelular() {
        return this.telCelular;
    }
    
    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Expertostema> getExpertostemas() {
        return this.expertostemas;
    }
    
    public void setExpertostemas(Set<Expertostema> expertostemas) {
        this.expertostemas = expertostemas;
    }
    public Set<Consulta> getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }




}


